language: ruby
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
notifications:
  email:
    - diego.domingues16@gmail.com
rvm:
  - 1.9.3
  - 2.1.2
branches:
  only:
    - master
    - 2-2-stable