language: ruby
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
notifications:
  email:
    - diego.domingues16@gmail.com
rvm:
  - 1.9.3
  - 2.1.2
branches:
  only:
    - master
    - 2-2-stable
    - 2-3-stable
addons:
  code_climate:
    repo_token: bff54e81747efae51a80babc7cadd216624d8166864c2350cba0886523b06afb